// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:qrcode_akillisletme/product/cache/hive_v2/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppCacheModelAdapter());
    registerAdapter(QrHistoryCacheModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppCacheModelAdapter());
    registerAdapter(QrHistoryCacheModelAdapter());
  }
}
